version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r myapp/requirements.txt

  build:
    commands:
      - echo Build started...
      - zip -r artifact.zip appspec.yml myapp/ scripts/
      - aws s3 cp artifact.zip s3://demo-zero-hero3/artifact.zip

artifacts:
  files:
    - artifact.zip
