version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r my_app/requirements.txt

  build:
    commands:
      - echo Build phase completed.

artifacts:
  files:
    - appspec.yml
    - scripts/**           # Include all scripts
    - my_app/**            # Include everything inside my_app
  discard-paths: no
