version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - cp -r templates /app/templates
      - cp app.py /app/
      - echo Starting app using Gunicorn...
      - gunicorn -b 0.0.0.0:8000 app:app &

artifacts:
  files:
    - app.py
    - templates/index.html
