version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - sudo apt-get update
      - sudo apt-get install -y nginx
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - echo Copying HTML templates...
      - sudo cp -r templates /var/www/html/
      # - sudo cp -r static /var/www/html/  # If you have static files
      - echo Copying application file...
      - cp app.py .

  post_build:
    commands:
      - echo Configuring Nginx...
      # Optional: Restart or configure Nginx if needed
      # - sudo systemctl restart nginx

artifacts:
  files:
    - app.py
    - templates/index.html
